### ISSUE TITLE
Make site accessible

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/techtonica.org#144]
Use accessibility guidelines we go over in that topic: https://github.com/Techtonica/curriculum/blob/master/accessibility/accessibility.md

**Comment by sniemar** [comment]
Hi! May I work on this issue?

**Comment by blueocto** [comment]
I submitted a PR for this last year, but it's still open :-/

**Comment by MichelleGlauser** [comment]
@rogue0137 Could you please take a look at this?

**Comment by rogue0137** [comment]
@MichelleGlauser yup; @blueocto is this it? https://github.com/Techtonica/techtonica.org/pull/158

**Comment by blueocto** [comment]
@MichelleGlauser @rogue0137  that will be the one!

**Comment by rogue0137** [comment]
@blueocto Awesome! I left a comment on the PR and added myself as a reviewer. When ready, re-request me as a reviewer and I can help merge it in :) Ty!!!!
