### ISSUE TITLE
Add privacy policy

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/techtonica.org#145]
Make it much like the /conduct page and use this template: https://docs.google.com/document/d/17cR90EvEd-2q-kfX8PrdkvoeihkGUQg4M2vIUN3sxJY/edit?usp=sharing

**Comment by charleycodes** [comment]
hi @MichelleGlauser! I want to be sure I understand the issue completely:

- create a `/privacy` route
- the content will be from the google doc you attached
- the styling will look like the `/conduct` page

Does that cover everything?

**Comment by charleycodes** [comment]
I'm also curious about what the contents of the `.env` file should be. The `EVENTBRITE_OATH_TOKEN` is referenced in `main_site.py` and that's it's defined in the `.env` file, but I don't see any additional information on how to populate this file.

**Comment by MichelleGlauser** [comment]
@charleycodes That's right! I can DM you the .env contents on Slack. Have you filled out our volunteer form so I can invite you?

**Comment by charleycodes** [comment]
@MichelleGlauser awesome! I've just completed it 😄

**Comment by MichelleGlauser** [comment]
@charleycodes I'd still love to have you sign up as an ongoing volunteer and to get you added to our Slack, and I don't see your name on the signup form. Hope you can fill it out: http://bit.ly/volunteer-with-Techtonica
