### ISSUE TITLE
Add a matching Instagram icon to the footer.

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/techtonica.org#151]
https://instagram.com/techtonicaorg/

**Comment by denamwangi** [comment]
How did you make the other icons?

**Comment by MichelleGlauser** [comment]
@denamwangi I can't remember! Hopefully someone has an image editor we can use to make a similar-looking round Instagram icon the right color (#0093B5).

**Comment by MichelleGlauser** [comment]
Done with https://github.com/Techtonica/techtonica.org/commit/03b932cdf8cb897667aebf832f2507742b681949.
