### ISSUE TITLE
[responsive] column on various pages is too wide (overflows) on small widths

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/techtonica.org#167]
I'm trying to fix this issue with my awesome CSS skills but I wanted to capture it here in case I can't figure it out or someone has some insights.

If you view the team page on Firefox responsible console or on, for example, Pixel 3a phone running Firefox, the text is cut off and it is difficult to read it. The home page does not have this problem so it must be a layout difference between them.

![2019-11-23 08 22 44](https://user-images.githubusercontent.com/355438/69481952-a752d580-0dca-11ea-8aa2-03c5a23656bc.png)

**Comment by Yashank18** [comment]
I will like to work on this.

**Comment by Yashank18** [comment]
I would like to work on this sir.

**Comment by vegetabill** [comment]
Sponsor page is also affected, merging #185 into this issue as we want a system-wide fix

**Comment by vegetabill** [comment]
Merged a report about the home page text into this issue

#184

**Comment by SaranshDawra** [comment]
@vegetabill I want to work on #185 issue.
