### ISSUE TITLE
Entirely remove PHP file from repo history

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/techtonica.org#17]
https://github.com/MichelleGlauser/techtonica/commit/4b063caf7d0879ef1ef14e6560287c5118573c90

**Comment by LizzHale** [comment]
I can take this on. I'll use the [filter-branch strategy](https://help.github.com/articles/remove-sensitive-data/#using-filter-branch) unless their are any objections. It involves a force push so I'll want to confirm that everyone is aware of this before I proceed as it re-writes the history in the repo.

**Comment by LizzHale** [comment]
Hi @MichelleGlauser -- no, this was not completed as I wasn't able to confirm that a force push was ok.

**Comment by MichelleGlauser** [comment]
Thanks, @LizzHale. Is there a potential problem if the history is re-written?

**Comment by LizzHale** [comment]
I'd expect [merge conflicts](https://mirrors.edge.kernel.org/pub/software/scm/git/docs/user-manual.html#problems-With-rewriting-history) so it's best for everyone working on the app to be aware of beforehand. That being said, it's the best solution I know of for removing sensitive information from the repository.

**Comment by vegetabill** [comment]
Just to clarify, is this a file with passwords or something sensitive? The link at the start is just php info, which only matters at runtime so I must be missing something. If there is something in the history that is private, we should definitely use the method described above and rotate all those passwords/keys. AFAIK it's the _only_ way to remove files.

**Comment by vegetabill** [comment]
@MichelleGlauser  ping on this issue. Let's close it unless action is needed.

**Comment by MichelleGlauser** [comment]
Whatever you think, @vegetabill.

**Comment by vegetabill** [comment]
File is not sensitive in terms of security so I see no reason to remove it.

Closing
