### ISSUE TITLE
Branch management proposal

### ISSUE THREAD

**Issue by gsong** [Techtonica/techtonica.org#177]
* Create a `develop` branch, which is the primary branch of the repo, and is the target of most PRs.
* `develop` should be deployed to staging for verification / smoke testing.
* `main` should track what's deployed to production.
* Tag in the form of `yyyy-mm-dd` should be applied to the commit which was deployed (this may not be necessary as the website doesn't change that frequently and doesn't have that many commits to wade through).

## Workflow

1. Branch off of develop for your feature branch development.
1. Once it’s good to go, merge your feature branch into develop.
1. Staging should run develop by default.
1. Once you’re happy, then you can merge develop into main.
1. Deploy main to production.

/cc @MichelleGlauser @vegetabill 

Address #175

**Comment by rogue0137** [comment]
@gsong I like this system; do you want it add this to the readme and we can start using it moving forward?

**Comment by gsong** [comment]
@celinaye Here's the issue dealing with Git branching workflow, if you want a starting point.

**Comment by krokoschke** [comment]
Updated Branch Managment in Readme and Updating Techtonicas Website https://github.com/Techtonica/techtonica.org/commit/920f9f718db6bba8cddeec7c68c1261a735d46ad#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
