### ISSUE TITLE
Don't require EVENTBRITE_OAUTH_TOKEN for local development

### ISSUE THREAD

**Issue by gsong** [Techtonica/techtonica.org#178]
`EVENTBRITE_OAUTH_TOKEN` is required in order to successfully spin up the local development environment currently. We should avoid that requirement to:

1. Reduce developer setup friction.
1. Prevent distributing secrets unnecessarily.

## Proposed Solution

Implement the following workflow:

```
isEventbriteClientInstantiated
  ? hasErrorFromEventRetrieval
    ? renderError()
    : areThereEvents
    ? renderEvents()
    : renderEmpty()
  : renderNoTokenScreen();
```

Address #175

**Comment by rogue0137** [comment]
hey @gsong, I'd like to take on this issue unless you have a PR I should review. Please let me know!
