### ISSUE TITLE
Create /volunteer top-level page

### ISSUE THREAD

**Issue by vegetabill** [Techtonica/techtonica.org#179]
List the different ways folks can help apart from donations of money/equipment.

Static list of Month of Year and what type of volunteering we are most in need of
- Bonus if it detects what month it is and showcases that at the top of the page

This came out of a planning meeting where @tiffquach and @vegetabill both said it would be helpful to have a URL to send to people who want to help.

**Comment by vegetabill** [comment]
@MichelleGlauser we created this while you were out to just double-checking there wasn't an intentional reason this wasn't on the site. We can also include a "financial donations are always needed" or some other disclaimer.

**Comment by MichelleGlauser** [comment]
Hopefully you saw that we already have a volunteer template and route. Just need to link to it somewhere.

**Comment by rogue0137** [comment]
@MichelleGlauser do you still want to update the "Mentor" link to "Volunteer"? If so, I can either  do it myself or let someone who wants the experience fix it. I can verify once there's a PR if the latter.

**Comment by MichelleGlauser** [comment]
@rogue0137 It looks like "Volunteer" is the link on the menu. Should this be closed?
