### ISSUE TITLE
Issue with responsiveness

### ISSUE THREAD

**Issue by goyalmuskan** [Techtonica/techtonica.org#184]
"The Upcoming Events" section is not responsive, I want to work on the issue!

![Screenshot (3)](https://user-images.githubusercontent.com/47412347/75601685-8691ce80-5ae3-11ea-8d0b-fc28d36427a5.png)

@vegetabill

**Comment by vegetabill** [comment]
Thank you for reporting this issue. It is already part of a known issue so I have merged your comment into issue, which already is being worked on.

Merging into #167
