### ISSUE TITLE
"Sponsor today to help Bridge TheTechGap" heading overflow in mobile view

### ISSUE THREAD

**Issue by SaranshDawra** [Techtonica/techtonica.org#185]
In sponsor page devices having a width less then 400px the heading is not responsive.

![Screenshot (91)](https://user-images.githubusercontent.com/50369485/75602309-f0ad7200-5ae9-11ea-8275-f902b722ad48.png)

@vegetabill I would like to work on this issue. Please assign me with this issue.

**Comment by vegetabill** [comment]
Thank you for reporting this issue. It is already part of a known issue so I have merged into that issue, which already is being worked on.

Merging into #167
