### ISSUE TITLE
Add more pictures to /mentor page and some quotes about participants working with mentors

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/techtonica.org#203]

**Comment by daaimah123** [comment]
Current participant quotes and images. Regarding this accomplished as of 10/30/24. 

<img width="1198" alt="Screenshot 2024-10-30 at 2 48 31 PM" src="https://github.com/user-attachments/assets/518080c3-21ec-45a4-8f63-9a687d8fd0ae">
<img width="1141" alt="Screenshot 2024-10-30 at 2 49 07 PM" src="https://github.com/user-attachments/assets/e1de3378-79e4-4c66-add5-a4ba3a037129">
<img width="1133" alt="Screenshot 2024-10-30 at 2 49 11 PM" src="https://github.com/user-attachments/assets/59502156-d880-447a-8657-934dd9585ed9">
