### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/techtonica.org#33]
Add a user-friendly blog to the website.

**Comment by yenly** [comment]
Does Techtonica have a Medium account? An idea is to write on Medium and use their [API](https://help.medium.com/hc/en-us/sections/203018828-API) with this [Medium SDK python wrapper](https://github.com/Medium/medium-sdk-python) to cross post back to Techtonica website.

**Comment by MichelleGlauser** [comment]
@aroseartist told me that Medium isn't good for analytics.

**Comment by MichelleGlauser** [comment]
We're still using Medium today.
