### ISSUE TITLE
Make button text consistent

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/techtonica.org#347]
Some of them have shadows and some don't.

**Comment by kushchoudhary98** [comment]
@MichelleGlauser can you provide more info about which buttons are you talking about.

**Comment by kushchoudhary98** [comment]
Ok, I can work on that. Should I start immediately or wait for it to be assigned to me?

**Comment by MichelleGlauser** [comment]
You can just start, @kushchoudhary98, but I just assigned it to you. Thank you!

**Comment by kushchoudhary98** [comment]
@MichelleGlauser I have created a PR that removes all text shadows.

**Comment by daaimah123** [comment]
@kushchoudhary98 thanks for applying the work so quickly! Can you please complete [this volunteer form](https://docs.google.com/forms/d/e/1FAIpQLSeW0mo-Dpsig70374UEPvzexpas-31Ost_HsFwm0kjNOxtbtg/viewform?c=0&w=1) so that I can make you a contributor on the repo.
