### ISSUE TITLE
Graphics on /sponsor/ are frighteningly large

### ISSUE THREAD

**Issue by phildini** [Techtonica/techtonica.org#352]
In attempting to find the Sponsor form for Techtonica, I browsed to /sponsor/ and started scrolling. "Frighteningly" may sound like hyperbole, but when I saw the size of these graphics, I actually said "AAH!" out loud.

This is on a 2560x1440 screen in Firefox on MacOS.

I have suggestions on how to fix if you'd like them but that seems presumptious to just drop them in.

![Screenshot 2024-08-26 at 15 34 30](https://github.com/user-attachments/assets/f7443b74-157b-479c-b203-723ee1c57bcf)
![Screenshot 2024-08-26 at 15 34 57](https://github.com/user-attachments/assets/61dcf51e-b9d8-4c39-8f06-81aac3aabbbb)

**Comment by MaggieFero** [comment]
@phildini Hello, and thank you for letting us know about this! To respond to the immediate need, our Partnerships form is available here: https://docs.google.com/forms/d/e/1FAIpQLSdNrE6qtdhND2eN3e4PbRfxa4ro1EKiQ3zYkKhYVxtbRXSsGg/viewform 

As for the apparently-giant graphics, I'll chat with the team about getting those fixed. I'm not sure any of us have a screen so large, though. Would you be alright with me tagging you here again to ask you to check when we think we've fixed it?

**Comment by phildini** [comment]
Yeah, happy to look at changes
