### ISSUE TITLE
Team page images are not aligned

### ISSUE THREAD

**Issue by gabymoreno9** [Techtonica/techtonica.org#367]
### 👉🏾 First time contributing to this repo? START HERE 👈🏾
To be added as a curriculum contributor and be assigned the related issue, please kindly complete [our contributor steps](https://github.com/Techtonica/curriculum/blob/efc365aba1bf1ea425060369751d2bc048174b22/CONTRIBUTING.md) in order to have your PR addressing this issue merged.

- ui issue where the team page images and content are not aligned like they used to be

![Screenshot 2024-10-04 at 14 52 07](https://github.com/user-attachments/assets/6b3a3b2d-fe6f-408b-a271-31a4ffb4cbdc)
![Screenshot 2024-10-04 at 14 53 09](https://github.com/user-attachments/assets/43b7e6ab-d8e5-464d-a1b7-2b4a7bbe6381)

**Comment by SirxChinni** [comment]
It seems interesting. I would like to work on this issue.
