### ISSUE TITLE
Add an anchor link to scroll down smoothly from hero image

### ISSUE THREAD

**Issue by akshayvinchurkar** [Techtonica/techtonica.org#56]
We should ad a anchor link at the top of the hero section for scroll down like this. i know this is small thing but it will add some interactivity to the hero section. we can also add subtle animation on it.

![index1](https://cloud.githubusercontent.com/assets/10510889/23398948/6fae3750-fdc4-11e6-80d2-cb9c28574bf5.jpg)

thinking about lots of things 
1 ) i also think about little parallax effect to the background of hero image.
2 ) also the font-smoothing issue on Firefox.
3 ) section under why section we should change the font-size of p tag.

if you guys allow me i will redesign this entire site with new layout

**Comment by MichelleGlauser** [comment]
Sounds good.

**Comment by akshayvinchurkar** [comment]
ok, so can I start with that? i mean redesign.

**Comment by MichelleGlauser** [comment]
@akshayvinchurkar: yes, that would be great! It would also be ideal if you could keep in mind that the site needs to be more friendly to potential sponsors as you re-design.

**Comment by akshayvinchurkar** [comment]
@MichelleGlauser cool. I will take care of that

**Comment by ananyakamboj** [comment]
Please assign me this issue
