### ISSUE TITLE
Embed Facebook share button

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/techtonica.org#70]
Details here: https://developers.facebook.com/docs/plugins/share-button (This is better because people can like the page and stay on the website.)

**Comment by aroseartist** [comment]
I would add this and still keep the static icon at the bottom.
Also suggest setting up the Google analytics social plugin:
https://developers.google.com/analytics/devguides/collection/analyticsjs/social-interactions

**Comment by hnarasaki** [comment]
@MichelleGlauser Where would you like the share button to be located?
