### ISSUE TITLE
Extra space to right side on mobile

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/techtonica.org#80]
The page can be moved to the left on iOS Safari and Android Chrome and extra space appears on the right side. 
![2017-03-26 21 25 13](https://cloud.githubusercontent.com/assets/1952773/24340921/c91a16e6-126a-11e7-96e9-ba46481e2cef.png)

**Comment by datadaveshin** [comment]
Was this issue fixed?
Page looks ok on my iPhone6s.

**Comment by datadaveshin** [comment]
Ok for Safari & Chrome on iPhone 6s iOS12
Ok for Firefox & Chrome using Android Samsung Galaxy Note 3.

**Comment by MichelleGlauser** [comment]
I think it's good! Thank you!
